//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public int Price { get; set; }
        public int MaxDiscount { get; set; }
        public int Manufacture { get; set; }
        public int Provider { get; set; }
        public int Category { get; set; }
        public int CurrentDiscount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Manufacture Manufacture1 { get; set; }
        public virtual Provider Provider1 { get; set; }
    }
}
